#Показ фильмов на сегодня
SELECT m.movie_id, m.movie_name FROM movies AS m WHERE m.premier_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '1 day';

#Формирование афиши на сегодня
SELECT m.movie_id, m.movie_name, h.hall_name, ms.date_of_start, ms.date_of_end FROM movies AS m
INNER JOIN movie_sessions AS ms ON m.movie_id = ms.movie_id
INNER JOIN halls AS h ON ms.hall_id = h.hall_id
WHERE ms.date_of_start BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '1 day';

#Подсчет кл-ва проданных билетов за неделю
SELECT COUNT(bt.booked_ticket_id) AS booked_tickets_count FROM booked_tickets AS bt WHERE bt.date_of_booked BETWEEN CURRENT_DATE - INTERVAL '1 week' AND CURRENT_DATE;

#Вывод трех самых прибыльных фильмов за неделю
SELECT m.movie_id, m.movie_name
FROM movies AS m
INNER JOIN movie_sessions AS ms ON m.movie_id = ms.movie_id
INNER JOIN tickets AS t ON ms.movie_session_id = t.movie_session_id
INNER JOIN booked_tickets AS bt ON t.ticket_id = bt.ticket_id
WHERE ms.date_of_start BETWEEN CURRENT_DATE - INTERVAL '7 days' AND CURRENT_DATE
GROUP BY m.movie_id, m.movie_name
ORDER BY SUM(t.ticket_price)
LIMIT 3;


#Вывод конкретного киносеанса с минимальной и максимальной стоимостью билета
SELECT m.movie_id, ms.movie_session_id, m.movie_name, MIN(t.ticket_price), MAX(t.ticket_price) FROM movies AS m
INNER JOIN movie_sessions AS ms ON m.movie_id = ms.movie_id
INNER JOIN tickets AS t ON ms.movie_session_id = t.movie_session_id
WHERE ms.movie_session_id = 1
GROUP BY m.movie_id, ms.movie_session_id, m.movie_name;


#Схема зала c показом свободных и занятых мест на конкретный сеанс
SELECT m.movie_id, ms.movie_session_id, m.movie_name, h.hall_name, hr.hall_row_number, p.place_number,
CASE
    WHEN bt.booked_ticket_id IS NULL THEN 'Свободно'
    ELSE 'Занято'
END AS place_status
FROM movies AS m 
INNER JOIN movie_sessions AS ms ON m.movie_id = ms.movie_id
INNER JOIN tickets AS t ON ms.movie_session_id = t.movie_session_id
LEFT JOIN booked_tickets AS bt ON t.ticket_id = bt.ticket_id
INNER JOIN places AS p ON t.place_id = p.place_id
INNER JOIN hall_rows AS hr ON p.hall_row_id = hr.hall_row_id
INNER JOIN halls AS h ON hr.hall_id = h.hall_id
WHERE ms.movie_session_id = 1
ORDER BY hr.hall_row_number, p.place_number;

#Визуальная схема зала
WITH hall_schema AS (
    SELECT m.movie_id, ms.movie_session_id, m.movie_name, h.hall_name, hr.hall_row_number, p.place_number,
    CASE
        WHEN bt.booked_ticket_id IS NULL THEN 'Свободно'
        ELSE 'Занято'
    END AS place_status
    FROM movies AS m 
    INNER JOIN movie_sessions AS ms ON m.movie_id = ms.movie_id
    INNER JOIN tickets AS t ON ms.movie_session_id = t.movie_session_id
    LEFT JOIN booked_tickets AS bt ON t.ticket_id = bt.ticket_id
    INNER JOIN places AS p ON t.place_id = p.place_id
    INNER JOIN hall_rows AS hr ON p.hall_row_id = hr.hall_row_id
    INNER JOIN halls AS h ON hr.hall_id = h.hall_id
    WHERE ms.movie_session_id = 1
    ORDER BY hr.hall_row_number, p.place_number
)
SELECT hs.hall_row_number, ARRAY_AGG(CASE WHEN hs.place_status = 'Свободно' THEN '|' || hs.place_number::varchar(3) || '|' ELSE '|B|' END) AS places FROM
hall_schema AS hs GROUP BY hs.hall_row_number;


#Для вывода размеров таблиц и индексов

#Выводим таблицы
WITH current_tables AS (
    SELECT (ARRAY['halls', 'hall_rows', 'places', 'movies', 'movie_sessions', 'tickets', 'booked_tickets', 'users', 'customers'])[i] AS current_table_name
    FROM generate_series(1, 9) AS i
),
current_tables_b AS (
    SELECT current_table_name, pg_table_size(current_table_name) AS table_size, pg_total_relation_size(current_table_name) AS total_table_size 
    FROM current_tables ORDER BY total_table_size DESC
)
SELECT current_table_name AS "Наименование таблицы", pg_size_pretty(table_size) AS "Размер таблицы", pg_size_pretty(total_table_size) AS "Размер таблицы с индексами"
FROM current_tables_b;

#Выводим индексы
WITH current_indexes AS (
    SELECT tablename, indexname FROM pg_indexes WHERE tablename IN ('halls', 'hall_rows', 'places', 'movies', 'movie_sessions', 'tickets', 'booked_tickets', 'users', 'customers')
),
current_indexes_b AS (
    SELECT tablename, indexname, pg_total_relation_size(CAST(indexname AS TEXT)) AS index_size FROM current_indexes ORDER BY index_size DESC
)
SELECT tablename AS "Наименование таблицы", indexname AS "Наименование индекса", pg_size_pretty(index_size) AS "Размер индекса" FROM current_indexes_b;