services:
  db-hw7:
    image: postgres:17-alpine
    ports:
      - "15432:5432"
    container_name: "db-hw7"
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./db:/var/lib/postgresql/data:rw
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql